#!/usr/bin/env python3
"""
scripts/demo_dynamic_options.py
===============================
Demonstrates that Jane's clarification options are 100% dynamically
generated by the LLM in real-time, tailored specifically to the user's
unique equipment, telemetry, and industrial domain.
"""

import sys
import os
import json

# Fix Windows console UTF-8 encoding
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

sys.path.insert(0, os.path.abspath("."))
from backend.jane_assistant import run_jane_assistant

domains = [
    (
        "Domain 1: Turbomachinery / Gas Turbines",
        "I have industrial gas turbine vibration and pressure sensor data. How can we build an ML model for this?"
    ),
    (
        "Domain 2: Renewable / Offshore Wind Turbines",
        "We are collecting 10-minute SCADA data from 50 offshore wind turbine pitch bearings and generator gearboxes."
    ),
    (
        "Domain 3: Chemical Process / Batch Reactor",
        "I have continuous pH, temperature, and agitation torque readings from an exothermic chemical batch reactor."
    ),
    (
        "Domain 4: Semiconductor / Plasma Etch",
        "I have wafer metrology thickness and plasma etch chamber RF power telemetry logs."
    )
]

print("=" * 75)
print("🌟 JANE DYNAMIC CLARIFICATION OPTIONS DEMONSTRATION")
print("=" * 75)

for title, prompt in domains:
    print(f"\n🏷️  [{title}]")
    print(f"💬 User: \"{prompt}\"")
    
    clean_id = title.split(":")[1].strip().lower().replace(" ", "_").replace("/", "_")
    sess_id = f"demo_dyn_{clean_id}"
    
    res = run_jane_assistant(session_id=sess_id, user_input=prompt)
    reply = res.get("reply", "")
    options = res.get("options", [])
    
    print("\n🤖 Jane Reply:")
    print(reply)
    print("\n📋 Extracted Dynamic Options:")
    for i, opt in enumerate(options, 1):
        print(f"   [{i}] {opt}")
    print("-" * 75)
